### ISSUE TITLE
Unit "kilocalorie/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".

### ISSUE THREAD

**Issue by kaokaoshuangyu** [zaixizhang/PocketGen#13]
Hello, I have a question
![Uploading 1ac8ccd9-8ccd-4882-a305-a4f330203641.png…]()

Could it be that I didn't load the dataset?

**Comment by kaokaoshuangyu** [comment]
The image has expired
![Uploading 1ac8ccd9-8ccd-4882-a305-a4f330203641.png…]()

**Comment by kaokaoshuangyu** [comment]
Traceback (most recent call last):
  File "generate_new.py", line 305, in <module>
    aar, rmsd, attend_logits = model.generate(batch, dir_name)
  File "/home/wangmei/01.work/005.Gen_20241213/PocketGen/models/PD.py", line 371, in generate
    to_pdb(label_X, batch['amino_acid'], batch['res_idx'], batch['amino_acid_batch'], self.generate_id, batch['protein_filename'], target_path, original=True)
  File "/home/wangmei/01.work/005.Gen_20241213/PocketGen/models/PD.py", line 543, in to_pdb
    openmm_relax(path)
  File "/home/wangmei/01.work/005.Gen_20241213/PocketGen/utils/relax.py", line 74, in openmm_relax
    simulation.minimizeEnergy(tolerance)
  File "/home/wangmei/miniconda3/envs/cuda/lib/python3.8/site-packages/openmm/app/simulation.py", line 143, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations, reporter)
  File "/home/wangmei/miniconda3/envs/cuda/lib/python3.8/site-packages/openmm/openmm.py", line 4422, in minimize
    tolerance = tolerance.value_in_unit(unit.kilojoules_per_mole/unit.nanometer)
  File "/home/wangmei/miniconda3/envs/cuda/lib/python3.8/site-packages/openmm/unit/quantity.py", line 626, in value_in_unit
    val = self.in_units_of(unit)
  File "/home/wangmei/miniconda3/envs/cuda/lib/python3.8/site-packages/openmm/unit/quantity.py", line 662, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "kilocalorie/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".

**Comment by kaokaoshuangyu** [comment]
Loading dataset...
  0%|                                                                                                                                                                      | 0/1 [00:00<?, ?it/s]0
./generate/2p16/2p16_pocket.pdb
                                                                                                                                                                                                Start Generating                                                                                                                                                            | 0/2 [00:00<?, ?it/s]
Test:   0%|                                                                                                                                                                | 0/2 [00:02<?, ?it/s]
  0%|                                                                                                                                                                      | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "generate_new.py", line 305, in <module>
    aar, rmsd, attend_logits = model.generate(batch, dir_name)
  File "/home/wangmei/01.work/005.Gen_20241213/PocketGen/models/PD.py", line 371, in generate
    to_pdb(label_X, batch['amino_acid'], batch['res_idx'], batch['amino_acid_batch'], self.generate_id, batch['protein_filename'], target_path, original=True)
  File "/home/wangmei/01.work/005.Gen_20241213/PocketGen/models/PD.py", line 543, in to_pdb
    openmm_relax(path)
  File "/home/wangmei/01.work/005.Gen_20241213/PocketGen/utils/relax.py", line 74, in openmm_relax
    simulation.minimizeEnergy(tolerance)
  File "/home/wangmei/miniconda3/envs/cuda/lib/python3.8/site-packages/openmm/app/simulation.py", line 143, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations, reporter)
  File "/home/wangmei/miniconda3/envs/cuda/lib/python3.8/site-packages/openmm/openmm.py", line 4422, in minimize
    tolerance = tolerance.value_in_unit(unit.kilojoules_per_mole/unit.nanometer)
  File "/home/wangmei/miniconda3/envs/cuda/lib/python3.8/site-packages/openmm/unit/quantity.py", line 626, in value_in_unit
    val = self.in_units_of(unit)
  File "/home/wangmei/miniconda3/envs/cuda/lib/python3.8/site-packages/openmm/unit/quantity.py", line 662, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "kilocalorie/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".

**Comment by jianwen350** [comment]
A solution working for me:
1. find the codes "tolerance = 2.39 * kilocalories_per_mole" and "simulation.minimizeEnergy(tolerance)" in the utils/relax.py.
2. change them to "tolerance_in_kj = 2.39 * unit.kilojoules_per_mole / unit.kilocalories_per_mole" and "simulation.minimizeEnergy(tolerance_in_kj)"
3. Save and Run

**Comment by zaixizhang** [comment]
The error seems to be caused by different package versions, I have updated the code following the suggestion! Thanks!
