### ISSUE TITLE
An openmm issue when trying to run generate_new.py

### ISSUE THREAD

**Issue by OrangeCat7777777** [zaixizhang/PocketGen#5]
Traceback (most recent call last):
  File "generate_new.py", line 307, in <module>
    aar, rmsd, attend_logits = model.generate(batch, dir_name)
  File "./models/PD.py", line 371, in generate
    to_pdb(label_X, batch['amino_acid'], batch['res_idx'], batch['amino_acid_batch'], self.generate_id, batch['protein_filename'], target_path, original=True)
  File "./models/PD.py", line 543, in to_pdb
    openmm_relax(path)
  File "./utils/relax.py", line 74, in openmm_relax
    simulation.minimizeEnergy(tolerance)
  File "~/envs/PocketGen/lib/python3.8/site-packages/openmm/app/simulation.py", line 143, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations, reporter)
  File "~/envs/PocketGen/lib/python3.8/site-packages/openmm/openmm.py", line 7009, in minimize
    tolerance = tolerance.value_in_unit(unit.kilojoules_per_mole/unit.nanometer)
  File "~/envs/PocketGen/lib/python3.8/site-packages/openmm/unit/quantity.py", line 626, in value_in_unit
    val = self.in_units_of(unit)
  File "~/envs/PocketGen/lib/python3.8/site-packages/openmm/unit/quantity.py", line 662, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "kilocalorie/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".

**Comment by OrangeCat7777777** [comment]
I reinstall openmm to match the version in pocketgen.yaml and the error is gone.
