### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by bio-rat** [zaixizhang/PocketGen#7]
Hi all,

I have been trying to install the dependency for this program for quite awhile but encountered many issues. This is the last one that I could not find a way to fix. I need some help!

`Traceback (most recent call last):
  File "/home/hung/miniconda3/envs/pocketgen/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "generate_new.py", line 55, in calculate_vina
    lig.get_pdbqt(ligand_pdbqt)
  File "/mnt/c/Users/etude/DL/PocketGen/utils/evaluation/docking_vina.py", line 21, in wrapper
    return func(*a, **ka)
  File "/mnt/c/Users/etude/DL/PocketGen/utils/evaluation/docking_vina.py", line 50, in get_pdbqt
    preparator.write_pdbqt_file(lig_pdbqt)
  File "/home/hung/miniconda3/envs/pocketgen/lib/python3.8/site-packages/meeko/preparation.py", line 129, in write_pdbqt_file
    raise RuntimeError('Cannot write PDBQT file %s.' % pdbqt_filename)
RuntimeError: Cannot write PDBQT file ./tmp/2lig.pdbqt.
"""`

**Comment by kweber1** [comment]
I had to create a tmp dir in the folder I was running in. It worked after that. Not sure if you are still having this issue or not.

**Comment by zaixizhang** [comment]
Thanks for the question! Yes, you could create a tmp dir in the folder. I will update the readme.
